name: Build and Deploy to EKS via ArgoCD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ---------- BUILD BACKEND ----------
    - name: Build backend image
      run: |
        docker buildx build --load \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest \
        ./backend

    # ---------- BUILD FRONTEND ----------
    - name: Build frontend image
      run: |
        docker buildx build --load \
        -t ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest \
        ./frontend

    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest

    - name: Update image tags in Helm chart
      run: |
        sed -i "s#image: .*fullstack-backend.*#image: \"${{ secrets.DOCKERHUB_USERNAME }}/fullstack-backend:latest\"#g" charts/fullstack/values.yaml
        sed -i "s#image: .*fullstack-frontend.*#image: \"${{ secrets.DOCKERHUB_USERNAME }}/fullstack-frontend:latest\"#g" charts/fullstack/values.yaml

    - name: Commit Helm changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add charts/fullstack/values.yaml
        git commit -m "ci: update image tags" || echo "No changes"
        git push
