name: Build and Deploy to EKS via ArgoCD

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Debug docker username secret
      run: echo "USERNAME=${{ secrets.DOCKERHUB_USERNAME }}"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ---------- BUILD BACKEND ----------
    - name: Build backend image
      run: docker buildx build --load -t vaishnavi126/fullstack-backend:latest ./backend

    # ---------- BUILD FRONTEND ----------
    - name: Build frontend image
      run: docker buildx build --load -t vaishnavi126/fullstack-frontend:latest ./frontend

    # ---------- DOCKER LOGIN ----------
    - name: DockerHub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # ---------- PUSH IMAGES ----------
    - name: Push Docker images
      run: |
        docker push vaishnavi126/fullstack-backend:latest
        docker push vaishnavi126/fullstack-frontend:latest

    # ---------- UPDATE HELM ----------
